# SELECT
SELECT * FROM `table`;
SELECT COUNT(*) FROM `table`;
SELECT `COLUMN` FROM `table` WHERE id = 1;

# JOIN
SELECT `COLUMN` FROM `table_A` AS A INNER JOIN `table_B` AS B ON A.Key = B.Key;
SELECT `COLUMN` FROM `table_A` AS A LEFT JOIN `table_B` AS B ON A.Key = B.Key;
SELECT `COLUMN` FROM `table_A` AS A RIGHT JOIN `table_B` AS B ON A.Key = B.Key;
SELECT `COLUMN` FROM `table_A` AS A FULL OUTER JOIN `table_B` AS B ON A.Key = B.Key;

# DISTINCT
SELECT DISTINCT `COLUMN` FROM `table`;

# FIND DUPLICATE VALUES (GROUP BY)
SELECT `COLUMN`, COUNT(*) AS cnt FROM `table` GROUP BY `COLUMN` HAVING cnt > 1;

# UPDATE
UPDATE `table` SET `COLUMN` = 'foo' WHERE id = 1;

# DELETE
DELETE FROM `table` WHERE id = 1;

# EXPLAIN QUERY
EXPLAIN SELECT * FROM `table`;

# DESCRIBE TABLE
DESCRIBE `table`;

# CHECK ALL VARIABLES
SHOW VARIABLES;

# CHECK MAX CONNECTIONS
SHOW VARIABLES LIKE 'max_connections';
